// Generated by Wrangler on Sun Feb 11 2024 15:27:55 GMT-0500 (Eastern Standard Time)
import { KVNamespace, D1Database } from '@cloudflare/workers-types'

interface Env {
	KV: KVNamespace;
	DB: D1Database;
}
